# Generated by Django 5.1.7 on 2026-01-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandals', '0004_crowdlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdlevel',
            name='time_slot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
