# Generated by Django 5.1.7 on 2026-01-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandals', '0005_crowdlevel_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdlevel',
            name='level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='crowdlevel',
            name='time_slot',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
    ]
