# Generated by Django 5.1.7 on 2026-01-14 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandals', '0006_alter_crowdlevel_level_alter_crowdlevel_time_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=200)),
                ('to_name', models.CharField(max_length=200)),
                ('from_lat', models.FloatField()),
                ('from_lng', models.FloatField()),
                ('to_lat', models.FloatField()),
                ('to_lng', models.FloatField()),
                ('mode', models.CharField(max_length=20)),
                ('distance', models.CharField(max_length=50)),
                ('eta', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
