# Generated by Django 5.1.7 on 2026-01-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandals', '0007_recentroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentroute',
            name='distance',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recentroute',
            name='eta',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recentroute',
            name='from_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recentroute',
            name='to_name',
            field=models.CharField(max_length=100),
        ),
    ]
